"""Shared constants."""

DEFAULT_CURRENCY = "CLP"
MONTHLY_EXCHANGE_RATE_CODES = frozenset({"UTM"})
UNEMPLOYMENT_INSURANCE_CONCEPT_CODE = "UNEMPLOYMENT_INSURANCE"
COMPUTED_CONTRIBUTION_CONCEPT_CODES = frozenset(
    {
        "PENSION_BASE",
        "PENSION_ADDITIONAL",
        "HEALTH_BASE",
        "HEALTH_ADDITIONAL_UF",
        UNEMPLOYMENT_INSURANCE_CONCEPT_CODE,
    }
)
INCOME_TAX_DEDUCTIBLE_CONCEPT_CODES = frozenset(
    {
        "PENSION_BASE",
        "PENSION_ADDITIONAL",
        "HEALTH_BASE",
        UNEMPLOYMENT_INSURANCE_CONCEPT_CODE,
    }
)
INCOME_TAX_CONCEPT_CODE = "INCOME_TAX"
REVIEW_REQUIRED_CONCEPT_CODES = COMPUTED_CONTRIBUTION_CONCEPT_CODES | frozenset(
    {INCOME_TAX_CONCEPT_CODE}
)
COMPLEMENTARY_INSURANCE_VALIDATION_PENDING_PREFIX = (
    "Complementary insurance validation pending: "
)
