"""Shared constants."""

DEFAULT_CURRENCY = "CLP"
COMPUTED_CONTRIBUTION_CONCEPT_CODES = frozenset(
    {
        "PENSION_BASE",
        "PENSION_ADDITIONAL",
        "HEALTH_BASE",
        "HEALTH_ADDITIONAL_UF",
        "UNEMPLOYMENT_INSURANCE",
    }
)
INCOME_TAX_CONCEPT_CODE = "INCOME_TAX"
REVIEW_REQUIRED_CONCEPT_CODES = COMPUTED_CONTRIBUTION_CONCEPT_CODES | frozenset(
    {INCOME_TAX_CONCEPT_CODE}
)
