"""Shared constants."""

DEFAULT_CURRENCY = "CLP"
DAILY_MARKET_RATE_CODES = ("USD", "EUR", "UF")
MONTHLY_MARKET_RATE_CODES = ("UTM",)
MONTHLY_ECONOMIC_INDEX_CODES = ("IPC_CL",)
MONTHLY_EXCHANGE_RATE_CODES = frozenset(MONTHLY_MARKET_RATE_CODES)
COMPUTED_CONTRIBUTION_CONCEPT_CODES = frozenset(
    {
        "PENSION_BASE",
        "PENSION_ADDITIONAL",
        "HEALTH_BASE",
        "HEALTH_ADDITIONAL_UF",
        "UNEMPLOYMENT_INSURANCE",
    }
)
INCOME_TAX_DEDUCTIBLE_CONCEPT_CODES = frozenset(
    {
        "PENSION_BASE",
        "PENSION_ADDITIONAL",
        "HEALTH_BASE",
        "UNEMPLOYMENT_INSURANCE",
    }
)
INCOME_TAX_CONCEPT_CODE = "INCOME_TAX"
REVIEW_REQUIRED_CONCEPT_CODES = COMPUTED_CONTRIBUTION_CONCEPT_CODES | frozenset(
    {INCOME_TAX_CONCEPT_CODE}
)
