-- ============================================================
-- Test-only seed data
-- ============================================================
-- Add non-production fixtures here.
-- This file is applied only through the explicit test-seed flow.
-- No current inserts were moved from db/seed.sql because the existing seed
-- contains production-safe reference and operational bootstrap data.
